const DAYS=[
{id:'mon',label:'Mon',title:'Push',focus:'Chest · Shoulders · Triceps'},
{id:'tue',label:'Tue',title:'Pull',focus:'Back · Biceps · Core'},
{id:'thu',label:'Thu',title:'Legs',focus:'Quads · Glutes · Calves'},
{id:'sat',label:'Sat',title:'Full Body',focus:'Strength · Skills · Core'}
];
const LEVELS=['beginner','intermediate','advanced','elite'];
const LEVEL_NAMES={beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',elite:'Elite'};
const LEVEL_DESC={beginner:'Learn technique and build a base',intermediate:'Build strength and control',advanced:'Increase intensity and skill',elite:'Maximum challenge and volume'};
const E={
 push:{name:'Push-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pushups.gif',muscles:['Chest','Triceps'],equipment:'Bodyweight',how:'Keep your body straight. Lower under control and push the floor away.',progression:['Incline push-up','Push-up','Diamond push-up','Decline push-up']},
 incline:{name:'Incline push-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pushups.gif',muscles:['Chest','Triceps'],equipment:'Stable table or counter',how:'Hands on a stable elevated surface, body straight, lower chest toward the surface.',progression:['Wall push-up','Incline push-up','Push-up']},
 pike:{name:'Pike push-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pike_Push_Ups.gif',muscles:['Shoulders','Triceps'],equipment:'Bodyweight',how:'Keep hips high and lower your head between your hands. Press back up.',progression:['Hands elevated','Floor pike push-up','Feet elevated','Handstand push-up']},
 diamond:{name:'Diamond push-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Narrow_Push_Ups.gif',muscles:['Triceps','Chest'],equipment:'Bodyweight',how:'Keep hands close together under your chest and keep elbows controlled.',progression:['Knee diamond','Diamond push-up','Slow diamond','Decline diamond']},
 dip:{name:'Chair dips',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bench-dips-1.png',muscles:['Triceps','Chest'],equipment:'Very stable chair',how:'Use a very stable chair. Bend elbows and press back up without dropping too deep.',progression:['Bent knees','Straight legs','Feet elevated']},
 plank:{name:'Plank',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Plank_exercise.svg',muscles:['Core','Shoulders'],equipment:'Bodyweight',how:'Keep ribs down, glutes tight and body straight. Breathe normally.',progression:['Knee plank','Plank','Long-lever plank','RKC plank']},
 row:{name:'Australian rows',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Body-row-1.png',muscles:['Upper back','Biceps'],equipment:'Low sturdy bar',how:'Keep the body rigid and pull your chest toward a sturdy horizontal surface.',progression:['Higher bar','Lower bar','Feet elevated']},
 pull:{name:'Pull-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pullup.gif',muscles:['Lats','Biceps','Upper back'],equipment:'Pull-up bar',how:'Start from a controlled hang and pull your chest toward the bar without swinging.',progression:['Dead hang','Scapular pull-up','Negative','Assisted pull-up','Pull-up','Chest-to-bar']},
 negative:{name:'Negative pull-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pullup.gif',muscles:['Lats','Biceps'],equipment:'Pull-up bar',how:'Start at the top and lower slowly for 3–5 seconds.',progression:['3 sec negative','5 sec negative','Assisted pull-up']},
 chin:{name:'Chin-ups',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chin-ups-1.png',muscles:['Biceps','Lats'],equipment:'Pull-up bar',how:'Use an underhand grip and pull the elbows down without kicking.',progression:['Assisted chin-up','Chin-up','Slow chin-up','Weighted chin-up']},
 raise:{name:'Hanging knee raises',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Legraises.gif',muscles:['Abs','Hip flexors'],equipment:'Pull-up bar',how:'Hang with straight arms and raise the knees without swinging.',progression:['Lying knee raise','Hanging knee raise','Straight-leg raise']},
 squat:{name:'Bodyweight squats',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bodyweight_Squats.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',how:'Sit the hips down between the feet and stand by driving through the whole foot.',progression:['Squat','Pause squat','Tempo squat','Jump squat']},
 tempo:{name:'Tempo squats',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bodyweight_Squats.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',how:'Use a slow controlled descent, brief pause, then stand strongly.',progression:['Squat','Tempo squat','Pause squat','Jump squat']},
 lunge:{name:'Reverse lunges',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lunge-CDC_strength_training_for_older_adults.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',how:'Step back, keep the torso stable and lower under control.',progression:['Assisted reverse lunge','Reverse lunge','Deficit reverse lunge']},
 bulgarian:{name:'Bulgarian split squats',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lunge-CDC_strength_training_for_older_adults.gif',muscles:['Quads','Glutes'],equipment:'Stable chair or bench',how:'Place the rear foot on a stable chair and lower the front leg under control.',progression:['Assisted split squat','Bulgarian split squat','Deficit split squat']},
 calf:{name:'Single-leg calf raises',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Standing-calf-raises-1.gif',muscles:['Calves'],equipment:'Bodyweight',how:'Rise through the ball of the foot and lower slowly.',progression:['Two-leg calf raise','Single-leg calf raise','Deficit single-leg raise']},
 bridge:{name:'Glute bridges',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bridge_exercise.svg',muscles:['Glutes','Hamstrings'],equipment:'Bodyweight',how:'Drive the hips up and squeeze the glutes without arching the lower back.',progression:['Bridge','Pause bridge','Single-leg bridge']},
 hollow:{name:'Hollow body holds',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/GMFT3-3_making_hollow_body.jpg',muscles:['Core'],equipment:'Bodyweight',how:'Press the lower back into the floor and hold a shallow curved position.',progression:['Tuck hold','One-leg hollow','Hollow hold']}
};
const PLANS={
mon:{beginner:[['Incline push-ups','3 × 8–12','incline'],['Push-ups','3 × 5–10','push'],['Plank','3 × 20–40 sec','plank'],['Chair dips','2 × 8–12','dip']],intermediate:[['Push-ups','4 × 8–15','push'],['Pike push-ups','3 × 6–12','pike'],['Diamond push-ups','3 × 6–12','diamond'],['Chair dips','3 × 8–15','dip'],['Plank','3 × 30–60 sec','plank']],advanced:[['Diamond push-ups','4 × 8–15','diamond'],['Pike push-ups','4 × 8–15','pike'],['Chair dips','4 × 10–15','dip'],['Push-ups','3 × 15–25','push'],['Plank','3 × 45–75 sec','plank']],elite:[['Diamond push-ups','5 × 10–20','diamond'],['Pike push-ups','4 × 10–18','pike'],['Chair dips','4 × 12–20','dip'],['Push-ups','3 × 20–30','push'],['Plank','4 × 60–90 sec','plank']]},
tue:{beginner:[['Australian rows','3 × 8–12','row'],['Negative pull-ups','3 × 3','negative'],['Chin-ups','2 × 3–6','chin'],['Hanging knee raises','2 × 6–10','raise']],intermediate:[['Pull-ups','4 × 3–10','pull'],['Australian rows','4 × 8–15','row'],['Negative pull-ups','3 × 3–6','negative'],['Chin-ups','3 × 4–10','chin'],['Hanging knee raises','3 × 8–15','raise']],advanced:[['Pull-ups','5 × 6–12','pull'],['Chin-ups','4 × 6–12','chin'],['Australian rows','4 × 12–20','row'],['Hanging knee raises','4 × 10–18','raise']],elite:[['Pull-ups','5 × 10–15','pull'],['Chin-ups','4 × 10–15','chin'],['Australian rows','4 × 15–25','row'],['Hanging knee raises','4 × 15–25','raise']]},
thu:{beginner:[['Bodyweight squats','3 × 10–15','squat'],['Reverse lunges','2 × 6–10 / leg','lunge'],['Glute bridges','3 × 10–15','bridge'],['Calf raises','3 × 12–20 / leg','calf']],intermediate:[['Bodyweight squats','4 × 10–20','squat'],['Reverse lunges','3 × 8–15 / leg','lunge'],['Bulgarian split squats','3 × 8–15 / leg','bulgarian'],['Single-leg calf raises','4 × 12–20 / leg','calf'],['Glute bridges','3 × 12–20','bridge'],['Plank','3 × 40–60 sec','plank']],advanced:[['Tempo squats','4 × 12–20','tempo'],['Bulgarian split squats','4 × 10–15 / leg','bulgarian'],['Reverse lunges','3 × 12–18 / leg','lunge'],['Single-leg calf raises','4 × 15–25 / leg','calf'],['Glute bridges','4 × 15–25','bridge']],elite:[['Tempo squats','5 × 15–25','tempo'],['Bulgarian split squats','5 × 12–20 / leg','bulgarian'],['Reverse lunges','4 × 15–20 / leg','lunge'],['Single-leg calf raises','5 × 20–30 / leg','calf'],['Glute bridges','4 × 20–30','bridge']]},
sat:{beginner:[['Incline push-ups','3 × 8–12','incline'],['Australian rows','3 × 8–12','row'],['Bodyweight squats','3 × 10–15','squat'],['Glute bridges','2 × 12–15','bridge'],['Plank','2 × 20–40 sec','plank']],intermediate:[['Push-ups','3 × 8–15','push'],['Pull-ups','3 × 4–10','pull'],['Bulgarian split squats','3 × 8–12 / leg','bulgarian'],['Pike push-ups','3 × 6–12','pike'],['Hanging knee raises','3 × 8–15','raise'],['Hollow body holds','3 × 20–40 sec','hollow']],advanced:[['Diamond push-ups','4 × 8–15','diamond'],['Pull-ups','4 × 6–12','pull'],['Bulgarian split squats','4 × 10–15 / leg','bulgarian'],['Pike push-ups','4 × 8–15','pike'],['Hanging knee raises','4 × 10–18','raise'],['Hollow body holds','3 × 30–50 sec','hollow']],elite:[['Diamond push-ups','5 × 10–20','diamond'],['Pull-ups','5 × 8–15','pull'],['Bulgarian split squats','5 × 12–20 / leg','bulgarian'],['Pike push-ups','4 × 10–18','pike'],['Hanging knee raises','4 × 15–25','raise'],['Hollow body holds','4 × 40–60 sec','hollow']]}
};
let currentDay=localStorage.getItem('ct-day')||'mon';
let level=localStorage.getItem('ct-difficulty')||'intermediate';
let state={};try{state=JSON.parse(localStorage.getItem('ct-state')||'{}')||{};}catch(e){state={};}
const REST_KEY='ct-rest-duration';
let restDuration=Number(localStorage.getItem(REST_KEY))||90;
let restRemaining=restDuration,restInterval=null,restRunning=false,restPaused=false;
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const save=()=>{localStorage.setItem('ct-day',currentDay);localStorage.setItem('ct-difficulty',level);localStorage.setItem('ct-state',JSON.stringify(state));localStorage.setItem(REST_KEY,String(restDuration));};
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=880;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.18,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.17);setTimeout(()=>c.close(),250);}catch(e){}}
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function updateTimer(){const d=document.getElementById('timerDisplay'),start=document.getElementById('timerStart'),reset=document.getElementById('timerReset'),presets=document.getElementById('timerPresets'),title=document.getElementById('timerTitle');if(d){d.textContent=fmt(restRemaining);d.hidden=!restRunning;d.classList.toggle('finished',restRemaining===0);}if(start)start.textContent=restRunning?(restPaused?'Resume':'Pause'):'Start';if(reset)reset.hidden=!restRunning;if(presets)presets.hidden=restRunning;if(title)title.textContent='Rest';document.querySelectorAll('.timer-preset').forEach(b=>{b.classList.toggle('active',Number(b.dataset.seconds)===restDuration);b.disabled=restRunning;});document.title=restRunning?`⏱ ${fmt(restRemaining)} · Calisthenics Tracker`:'Calisthenics Tracker';}
function stopTimer(){clearInterval(restInterval);restInterval=null;restRunning=false;restPaused=false;}
function finishTimer(){stopTimer();restRemaining=0;updateTimer();beep();setTimeout(beep,220);if(navigator.vibrate)navigator.vibrate([100,80,180]);setTimeout(()=>{restRemaining=restDuration;updateTimer();},1300);}
function tick(){if(!restRunning||restPaused)return;restRemaining=Math.max(0,restRemaining-1);if(restRemaining>0&&restRemaining<=3)beep();if(restRemaining===0)finishTimer();else updateTimer();}
function startTimer(){if(restRunning){restPaused=!restPaused;updateTimer();return;}restRemaining=restDuration;restRunning=true;restPaused=false;updateTimer();beep();clearInterval(restInterval);restInterval=setInterval(tick,1000);}
function resetTimer(){stopTimer();restRemaining=restDuration;updateTimer();}
function chooseRest(seconds){restDuration=seconds;localStorage.setItem(REST_KEY,String(seconds));resetTimer();}
function setCount(target){const m=String(target).match(/^(\d+)/);return m?Number(m[1]):1;}
function renderTabs(){document.getElementById('tabs').innerHTML=DAYS.map(d=>`<button class="tab ${d.id===currentDay?'active':''}" data-day="${d.id}" type="button"><strong>${d.label}</strong><br>${d.title}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentDay=b.dataset.day;save();render();});}
function renderDifficulty(){const p=document.getElementById('difficultyPicker');p.innerHTML=LEVELS.map(x=>`<button class="difficulty-option ${x===level?'active':''}" data-level="${x}" type="button">${LEVEL_NAMES[x]}</button>`).join('');p.querySelectorAll('button').forEach(b=>b.onclick=()=>{level=b.dataset.level;save();render();});document.getElementById('difficultyDescription').textContent=LEVEL_DESC[level];}
function renderStats(plan){const total=plan.length;let done=0;plan.forEach((_,i)=>{const s=state[`${currentDay}-${level}-${i}`];if(s?.complete)done++;});const pct=total?Math.round(done/total*100):0;document.getElementById('stats').innerHTML=`<div class="stat"><div class="stat-label">Exercises</div><div class="stat-value">${total}</div></div><div class="stat"><div class="stat-label">Completed</div><div class="stat-value">${done}/${total}</div></div><div class="stat wide"><div class="stat-label">Progress</div><div class="progress-wrap"><div class="progress-bar" style="width:${pct}%"></div></div><div class="hint">${pct}% complete · ${DAYS.find(d=>d.id===currentDay).focus}</div></div>`;}
function renderWorkout(plan){const main=document.getElementById('workout');main.innerHTML=plan.map((x,i)=>{const [name,target,id]=x,e=E[id],s=state[`${currentDay}-${level}-${i}`]||{},sets=setCount(target),doneSets=s.setsDone||[];return `<article class="exercise ${s.complete?'completed':''}" data-index="${i}"><div class="row"><div><div class="name">${esc(name)}</div><div class="target">${esc(target)}</div></div><button class="btn extend" type="button">Extend</button></div><div class="details"><div class="media-frame"><img src="${e.media}" alt="Demonstration of ${esc(e.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="media-fallback" style="display:none"><strong>${esc(e.name)}</strong><span>Demo unavailable</span></div></div><div class="meta-grid"><div><span>Equipment</span><strong>${esc(e.equipment)}</strong></div><div><span>Difficulty</span><strong>${'★'.repeat(Math.min(5,Math.max(1,Math.round(i+1))))}</strong></div></div><div class="chips">${e.muscles.map(m=>`<span>${esc(m)}</span>`).join('')}</div><div class="tip"><strong>How to:</strong> ${esc(e.how)}</div><div class="progression"><strong>Progression</strong><div>${e.progression.map((p,n)=>`${n?' <span class="arrow">→</span>':''}<span class="step">${esc(p)}</span>`).join('')}</div></div><div class="sets">${Array.from({length:sets},(_,j)=>`<div class="set"><label>Set ${j+1}<input inputmode="numeric" placeholder="reps" value="${esc(s.reps?.[j]||'')}"></label><button type="button" class="set-done ${doneSets[j]?'done':''}">${doneSets[j]?'Done ✓':'Done'}</button></div>`).join('')}</div><button type="button" class="exercise-complete ${s.complete?'done':''}">${s.complete?'Exercise completed ✓':'Complete exercise'}</button></div></article>`;}).join('');
main.querySelectorAll('.extend').forEach(b=>b.onclick=()=>b.closest('.exercise').classList.toggle('open'));
main.querySelectorAll('.exercise').forEach(card=>{const i=Number(card.dataset.index),k=`${currentDay}-${level}-${i}`,s=state[k]||{};card.querySelectorAll('input').forEach((input,j)=>input.oninput=()=>{s.reps=s.reps||[];s.reps[j]=input.value;state[k]=s;save();});card.querySelectorAll('.set-done').forEach((b,j)=>b.onclick=()=>{s.setsDone=s.setsDone||[];s.setsDone[j]=!s.setsDone[j];state[k]=s;save();b.classList.toggle('done',s.setsDone[j]);b.textContent=s.setsDone[j]?'Done ✓':'Done';if(s.setsDone[j]){startTimer();const next=card.querySelectorAll('.set')[j+1];if(next)setTimeout(()=>next.scrollIntoView({behavior:'smooth',block:'center'}),150);else{const nextCard=card.nextElementSibling;if(nextCard)setTimeout(()=>nextCard.scrollIntoView({behavior:'smooth',block:'center'}),150);}}renderStats(plan);});card.querySelector('.exercise-complete').onclick=()=>{s.complete=!s.complete;state[k]=s;save();renderStats(plan);card.classList.toggle('completed',s.complete);};});}
function render(){renderTabs();renderDifficulty();const plan=PLANS[currentDay][level]||[];renderStats(plan);renderWorkout(plan);updateTimer();}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.timer-preset').forEach(b=>b.onclick=()=>chooseRest(Number(b.dataset.seconds)));document.getElementById('timerStart').onclick=startTimer;document.getElementById('timerReset').onclick=resetTimer;render();});